##################################
#   TelegramChat Main Config
#   Made by ParamountDev
#   TG-Link: @paramount1_dev
#   FunPay: https://funpay.com/uk/users/14397429/
##################################

# Do not change this value.
author: "ParamountDev"


# Read the guide.txt before using plugin.

# Bot configuration. Put your bot token and bot username in fields below.
telegram:
  bot-token: "YOUR_BOT_TOKEN"
  bot-username: "@YOUR_USERNAME_HERE"


# Voice messages configuration. Put your Vosk Model folder name in fields below.
voice-messages:
  vosk_model: "FOLDER_NAME"

# Image messages configuration.
image-messages:
  lifetime: 60   # seconds