name: TelegramChat
version: '1.0'
main: dev.paramountdev.telegramChat.TelegramChat
api-version: '1.21'

depend:
  - ImageFrame

author: ParamountDev

commands:
  tgchat:
    usage: /tgchat
  showimage:
    usage: /showimage name
  listenvoice:
    usage: /listenvoice <id>






